= Ansible Ecosystem: Information, Tips, Best Practices
:author: Thorsten Winkler
:email: thorsten.winkler@de.ibm.com
:revdate: {docdate}
:revnumber: 0.1
:revremark: Remark {revnumber}
:version-label: Version
:toc:
:toclevels: 4
:toc-title: Table of Contents
:sectnums: |,all|
//:source-highlighter: pygments
//:pygments-style: material
//:pygments-css: class
//:pygments-linenums-mode: table
//:source-highlighter: highlight.js
//:highlightjs-theme: base16/gruvbox-dark-pale
//:highlightjsdir: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0


== Ansible

=== Installation

==== Global installation

 $ test


.Optional Title
****
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.
****

TIP: Test dsad asd sad sa dsa dsa dsa dsa adsa dsa dsa dsad

.Optional Title
[source, bash]
----
#!/bin/bash
# Ansible installation
pip install ansible

# Ansible upgrade
pip install --upgrade ansible
if [[ $UID -eq 1]]
then
fi
----

.dasda
==========================
*Example* Block

Use: examples :)

Default caption "Example:"
can be changed using

 [caption="Custom: "]

before example block.
==========================


==== Local installation

[source, bash, linenums]
----
# Example installation in an independent local virtual environment
python -m venv venv-ansible-installation
source venv-ansible-installation/bin/activate
pip install --upgrade pip
pip install ansible
----

### Inventory

List all hosts of playbook/inventory file (default location: /etc/ansible/
hosts):

```bash
ansible-inventory -i hosts --graph
ansible-inventory -i hosts --list
```

### Roles

- Role directory structure
  - https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
- Dependencies to other roles defined in
  
  - `<path-to-roles>/<role_name>/meta/main.yml`

    ```bash
    # cat <path-to-roles>/<role_name>/meta/main.yml:
    - dependencies: []
    ```

- [Create roles with ansible galaxy](#121-create-new-ansible-role)
- [Create roles with molecule](#132-create-new-ansible-role-with-molecule)

### Plugins

- Get list of available plugins:\
  `$ ansible-doc -t lookup -l`
- List of plugin types (and therefore directory names for development)
  - https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-a-plugin-locally
- Lookup plugins:
  - https://docs.ansible.com/ansible/latest/plugins/lookup.html

## Ansible Galaxy

### Create new ansible role

- https://galaxy.ansible.com/docs/contributing/creating_role.html

  ```bash
  # ansible-galaxy init --init-path <path-to-roles> <role_name>
  $ ansible-galaxy init --init-path . ar-common
  $ ls -la ./ar-common
      8 -rw-r--r--  1 user  staff   1,3K 15 Aug 13:13 .travis.yml
      8 -rw-r--r--  1 user  staff   1,3K 15 Aug 13:13 README.md
      0 drwxr-xr-x  3 user  staff    96B 15 Aug 13:13 defaults/
      0 drwxr-xr-x  2 user  staff    64B 15 Aug 13:13 files/
      0 drwxr-xr-x  3 user  staff    96B 15 Aug 13:13 handlers/
      0 drwxr-xr-x  3 user  staff    96B 15 Aug 13:13 meta/
      0 drwxr-xr-x  3 user  staff    96B 15 Aug 13:13 tasks/
      0 drwxr-xr-x  2 user  staff    64B 15 Aug 13:13 templates/
      0 drwxr-xr-x  4 user  staff   128B 15 Aug 13:13 tests/
      0 drwxr-xr-x  3 user  staff    96B 15 Aug 13:13 vars/
  ```

### Install multiple roles from a file

- https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file
- Create yaml file `<requirements.yml>`

  ```bash
  ---
  # from Github
  - src: https://github.com/bennojoy/nginx
  # from galaxy
  - src: yatesr.timezone
  ...
  ```

- Run the following command

  ```bash
  ansible-galaxy install -r requirements.yml
  ```

## 1.3. Molecule - Ansible Testing

- https://molecule.readthedocs.io
- Keep in mind that Ansible itself says that an extra testing framework isn't necessary:
  https://docs.ansible.com/ansible/latest/reference_appendices/test_strategies.html#conclusion 
  > Ansible believes you should not need another framework to validate basic things of your infrastructure is true. This is the case because Ansible is an order-based system that will fail immediately on unhandled errors for a host, and prevent further configuration of that host. This forces errors to the top and shows them in a summary at the end of the Ansible run.

  But due to creating roles for multiple operating systems, I prefer to have the option to test changes immediately on different operating systems. Therefore I want to integrate molecule as often as possible.

### Installation via pip

- https://molecule.readthedocs.io/en/latest/installation.html
- > It is highly recommended that you install molecule in a virtual environment!
- Install the following molecule drivers

  ```bash
  pip install --upgrade setuptools
  pip install "molecule[docker]"
  pip install "molecule[lint]"
  pip install "molecule[podman]"
  # same than
  # pip install "molecule[docker,lint,podman]
  ```

### Create new ansible role with molecule

- https://molecule.readthedocs.io/en/latest/getting-started.html#creating-a-new-role
- > Molecule uses galaxy under the hood to generate conventional role layouts

  ```bash
  # molecule init role my-new-role --driver-name docker 
  $ molecule init role ar-common-molecule --driver-name docker 
  $ ls -la ar-common-molecule 
      8 -rw-r--r--  1 thwi  staff   539B Dec 23 12:19 .travis.yml
      8 -rw-r--r--  1 thwi  staff   598B Dec 23 12:19 .yamllint
      8 -rw-r--r--  1 thwi  staff   1.3K Dec 23 12:19 README.md
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 defaults/
      0 drwxr-xr-x  2 thwi  staff    64B Dec 23 12:19 files/
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 handlers/
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 meta/
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 molecule/
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 tasks/
      0 drwxr-xr-x  2 thwi  staff    64B Dec 23 12:19 templates/
      0 drwxr-xr-x  4 thwi  staff   128B Dec 23 12:19 tests/
      0 drwxr-xr-x  3 thwi  staff    96B Dec 23 12:19 vars/
  ```

### Molecule Scenarios

- https://molecule.readthedocs.io/en/latest/getting-started.html#molecule-scenarios
- Every folder in `ar-common-molecule/molecule/<folder>` represents a molecule scenario
- And every scenario contains the following files:

  - `INSTALL.rst`: Info und install instructions
  - `molecule.yml`: Central configuration entrypoint for molecule. Molecule invokes this playbook with `ansible-playbook` and run it against an instance created by the driver
  - `verify.yml`: is the Ansible file used for testing as Ansible is the default Verifier.

## Useful links/information/discussions/questions/decisions

* Turorials:
** https://www.informatik-aktuell.de/entwicklung/programmiersprachen/einfuehrung-in-ansible.html

* Best Practices:
** https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

* YAML Syntax:
** https://yaml.org/refcard.html
** https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

* Ansible lookups: vars vs. facts
** https://opensolitude.com/2015/05/27/ansible-lookups-variables-vs-facts.html

* vars_vs_facts.footnote:iwas[https://opensolitude.com/2015/05/27/ansible-lookups-variables-vs-facts.html]: https://opensolitude.com/2015/05/27/ansible-lookups-variables-vs-facts.html

* vars_vs_facts.footnote:iwas[]: https://opensolitude.com/2015/05/27/ansible-lookups-variables-vs-facts.html

[bibliography]
== References

* [[[ad,ansible-docs]]] Ansible Docs - https://docs.ansible.com/
- Ansible Galaxy Docs - https://galaxy.ansible.com/docs/
- Ansible Galaxy User Guide - https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
- Molecule - Ansible Testing - https://molecule.readthedocs.io
